servers:
  - url: ''
openapi: 3.0.3
info:
  description: API Description
  title: Bike Predictions
  version: 1.0.0
paths:
  /predict:
    post:
      summary: 'Predict duration'
      responses:
        default:
          description: Default response.
      parameters: []
      requestBody:
        description: Bike data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
               start_station_id:
                type: integer
                title: "Start station ID"
                example: 49
               end_station_id:
                type: integer
                title: "End station ID"
                example: 34
               hour_started:
                type: integer
                title: "Hour the bike ride started"
                example: 10
               started_at:
                type: integer
                title: "Date of the trip"
                example: "2020-11-01"
               