name: update model
on:
  schedule:
    - cron:  '0 0 * * *'
    - [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest   
    container: mortensen0/base-bysykkel:v2
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        Rscript -e 'source("update_model.R")'
    - name: Commit files
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Scheduled model update"
        git push
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}