
on: [push]
name: Build and deploy container

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            # Merk at dockerfilen ligger i predict_duration/
            # Navnet på imaget som bygges blir bysykkel:{github.sha}
            docker build predict_duration/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/bysykkel:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/bysykkel:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }} # Url til api
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/bysykkel:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-bysykkel # Navn på ACI-ressurs
            location: 'north europe'

